#!/bin/bash

REPO_OWNER="MR-MKZ"
REPO_NAME="mirzabot"
INSTALL_DIR="/var/www/html"
BOT_SUBDIR="mirzaprobotconfig"
TARGET_DIR="$INSTALL_DIR/$BOT_SUBDIR"
CONFIG_FILE="$TARGET_DIR/config.php"

telegram_retry() {
    local max_retries=5
    local attempt=1
    local delay=2

    while [ $attempt -le $max_retries ]; do
        response=$("$@")
        
        # Success check
        if echo "$response" | grep -q '"ok":true'; then
            echo "✅ Success."
            return 0
        fi

        if echo "$response" | grep -q '"error_code":429'; then
            retry_after=$(echo "$response" | jq -r '.parameters.retry_after // 5')
            echo "⚠️  Rate limited. Sleeping for ${retry_after}s..."
            sleep "$retry_after"
        else
            echo "❌ API Error: $response"
            sleep $delay
        fi

        ((attempt++))
    done
    
    echo "❌ Failed after $max_retries attempts."
    return 1
}

echo "Target Directory: $TARGET_DIR"

if [ -z "$(ls -A $TARGET_DIR 2>/dev/null)" ]; then
    echo "Directory empty. Fetching $BOT_VERSION from GitHub..."
    mkdir -p "$TARGET_DIR"

    if [ "$BOT_VERSION" == "latest" ] || [ -z "$BOT_VERSION" ]; then
        DOWNLOAD_URL=$(curl -s "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/releases/latest" | jq -r '.zipball_url')
    else
        DOWNLOAD_URL="https://github.com/$REPO_OWNER/$REPO_NAME/archive/refs/tags/$BOT_VERSION.zip"
    fi
    
    if [ -z "$DOWNLOAD_URL" ] || [ "$DOWNLOAD_URL" == "null" ]; then
        echo "⚠️  API fetch failed or no release found. Falling back to main branch..."
        DOWNLOAD_URL="https://github.com/$REPO_OWNER/$REPO_NAME/archive/refs/heads/main.zip"
    fi

    echo "Downloading from: $DOWNLOAD_URL"
    
    curl -L -o /tmp/bot.zip "$DOWNLOAD_URL"
    
    TEMP_EXTRACT="/tmp/bot_extract"
    rm -rf "$TEMP_EXTRACT"
    mkdir -p "$TEMP_EXTRACT"
    unzip -q /tmp/bot.zip -d "$TEMP_EXTRACT"
    
    EXTRACTED_FOLDER=$(find "$TEMP_EXTRACT" -mindepth 1 -maxdepth 1 -type d | head -n 1)
    
    if [ -d "$EXTRACTED_FOLDER" ]; then
        echo "Moving files to $TARGET_DIR..."
        cp -r "$EXTRACTED_FOLDER/"* "$TARGET_DIR/"
        echo "Files extracted successfully."
    else
        echo "❌ Error: Could not find extracted folder."
        ls -la "$TEMP_EXTRACT"
        exit 1
    fi
    
    rm -rf /tmp/bot.zip "$TEMP_EXTRACT"
    chown -R www-data:www-data "$TARGET_DIR"
    chmod -R 755 "$TARGET_DIR"
fi

if [ ! -f "$CONFIG_FILE" ] || grep -q "{database_name}" "$CONFIG_FILE"; then
    echo "⚠️  Broken or missing config detected. Overwriting..."
    
    SECRET_TOKEN=$(openssl rand -base64 10 | tr -dc 'a-zA-Z0-9' | cut -c1-8)
    
    cat <<EOF > "$CONFIG_FILE"
<?php
// Generated by Docker | Mr.MKZ

// This variable added for high load panels which their response time is long and bot can't communicate with online panel!
// null for default settings
\$request_exec_timeout = ${REQUEST_TIMEOUT:-null};
\$dbhost = '${DB_HOST}';
\$dbname = '${DB_NAME}';
\$usernamedb = '${DB_USER}';
\$passworddb = '${DB_PASS}';

\$connect = mysqli_connect(\$dbhost, \$usernamedb, \$passworddb, \$dbname);
if (\$connect->connect_error) { die("error" . \$connect->connect_error); }
mysqli_set_charset(\$connect, "utf8mb4");

\$options = [ PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC, PDO::ATTR_EMULATE_PREPARES => false, ];
\$dsn = "mysql:host=\$dbhost;dbname=\$dbname;charset=utf8mb4";

try { 
    \$pdo = new PDO(\$dsn, \$usernamedb, \$passworddb, \$options); 
} catch (\PDOException \$e) { 
    error_log("Database connection failed: " . \$e->getMessage()); 
}

\$APIKEY = '${API_KEY}';
\$adminnumber = '${ADMIN_ID}';
\$domainhosts = '${DOMAIN_HOST}';
\$usernamebot = '${BOT_USERNAME}';
\$secrettoken = '${SECRET_TOKEN}';
?>
EOF
    chown www-data:www-data "$CONFIG_FILE"
    echo "✅ Config.php generated successfully."

    # Run Database Setup
    echo "⏳ Waiting for Database to be ready..."
    sleep 5
    if [ -f "$TARGET_DIR/table.php" ]; then
        php "$TARGET_DIR/table.php" || echo "❌ Warning: table.php execution failed."
    else
        echo "❌ Error: table.php not found at $TARGET_DIR/table.php"
    fi

    echo "🔗 Setting Telegram Webhook..."
    CLEAN_DOMAIN="${DOMAIN_HOST#*://}"
    WEBHOOK_URL="https://${CLEAN_DOMAIN}/index.php"
    
    telegram_retry curl -s -X POST "https://api.telegram.org/bot${API_KEY}/setWebhook" \
        -F "url=${WEBHOOK_URL}" \
        -F "secret_token=${SECRET_TOKEN}"

    echo "📩 Sending Notification..."
    MESSAGE="✅ MirzaBot installed successfully via Docker."
    telegram_retry curl -s -X POST "https://api.telegram.org/bot${API_KEY}/sendMessage" \
        -d chat_id="${ADMIN_ID}" \
        -d text="$MESSAGE"

else
    echo "✅ Config file exists and is valid."
fi

echo "🚀 Starting Supervisor..."
exec /usr/bin/supervisord

